### ISSUE TITLE
[CI 建议] 启用Build Scan (?)

### ISSUE THREAD

**Issue by qhy040404** [LibChecker/LibChecker#339]
#319 的补充

启用Gradle Build Scan需要修改传入gradle的参数，示例如下:
```yaml
- name: Check style
  uses: gradle/gradle-build-action@v2
  with:
    arguments: lintKotlin --scan
```

---

未启用：![](https://img.shields.io/badge/Build%20Scan%E2%84%A2-NOT_PUBLISHED-lightgrey?logo=Gradle)

已启用：![](https://img.shields.io/badge/Build%20Scan%E2%84%A2-PUBLISHED-06A0CE?logo=Gradle)

---

主要是看到了相关的PR，但是没有看到Build Scan的启用
